[project]
name = "financial-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.141.1",
    "langchain>=1.4.2",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.12",
    "pandas>=3.0.6",
]
